version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_pass
      POSTGRES_DB: delivery_db
    ports:
      - "35432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
